language: python
python:
  - "2.7"
  - "3.4"
install: 
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install coverage"
    - "pip install coveralls"
    - "pip install pytest-cov"
script:
    - "py.test --cov flask_sandboy --cov-report term-missing"
after_success:
    coveralls
